force-app/main/default/objects/ExtraObject__c/ExtraObject__c.object-meta.xml
<CustomObject>
    <label>ExtraObject</label>
    <nameField>
        <label>AnotherTestingObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExtraObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ExtraObject__c/fields/ExtraField__c.field-meta.xml
<CustomField>
    <fullName>ExtraField__c</fullName>
    <label>ExtraField</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TestingObject__c/TestingObject__c.object-meta.xml
<CustomObject>
    <label>TestingObject</label>
    <nameField>
        <label>TestingObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TestingObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TestingObject__c/fields/TestingField__c.field-meta.xml
<CustomField>
    <fullName>TestingField__c</fullName>
    <label>TestingField</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestingObjectController.cls
public with sharing class TestingObjectController {
	public static List<TestingObject__c> updateTestingObjects() {
		List<TestingObject__c> updatedRecords = new List<TestingObject__c>();

		try {
			List<TestingObject__c> testingObjects = [
				SELECT Id, TestingField__c
				FROM TestingObject__c
			];

			ExtraObject__c latestExtraObject = [
				SELECT ExtraField__c
				FROM ExtraObject__c
				ORDER BY CreatedDate DESC
				LIMIT 1
			];

			for (TestingObject__c testingRecord : testingObjects) {
				testingRecord.TestingField__c = latestExtraObject.ExtraField__c;
			}

			Database.update(testingObjects, true);

			updatedRecords = testingObjects;
		} catch (Exception e) {
			System.debug(e.getMessage());
		}

		return updatedRecords;
	}
}