force-app/main/default/objects/ExtraObject__c/ExtraObject__c.object-meta.xml
<CustomObject>
    <label>ExtraObject</label>
    <nameField>
        <label>AnotherTestingObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExtraObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ExtraObject__c/fields/ExtraField__c.field-meta.xml
<CustomField>
    <fullName>ExtraField__c</fullName>
    <label>ExtraField</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TestingObject__c/TestingObject__c.object-meta.xml
<CustomObject>
    <label>TestingObject</label>
    <nameField>
        <label>TestingObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TestingObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TestingObject__c/fields/TestingField__c.field-meta.xml
<CustomField>
    <fullName>TestingField__c</fullName>
    <label>TestingField</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestingObjectControllerTest.cls
@IsTest
public with sharing class TestingObjectControllerTest {
	@IsTest
	static void testTestingObjectsUpdate() {
		List<SObject> insertableRecords = new List<SObject>();
		ExtraObject__c extraRecord = new ExtraObject__c(
			ExtraField__c = 'QFXBR'
		);
		TestingObject__c testingRecord = new TestingObject__c(
			TestingField__c = 'defaultValue'
		);
		TestingObject__c additionalTestingRecord = new TestingObject__c(
			TestingField__c = 'defaultValue'
		);

		insertableRecords.add(testingRecord);
		insertableRecords.add(additionalTestingRecord);
		insertableRecords.add(extraRecord);

		Database.insert(insertableRecords, true);

		Test.startTest();

		List<TestingObject__c> updatedRecords = TestingObjectController.updateTestingObjects();

		for (TestingObject__c updated : updatedRecords) {
			System.assert(
				updated.TestingField__c == extraRecord.ExtraField__c,
				'There is a mismatch between testingRecords and extraRecord.'
			);
		}

		Test.stopTest();
	}

	@IsTest
	static void testUpdateException() {
		List<SObject> insertableRecords = new List<SObject>();
		TestingObject__c testingRecord = new TestingObject__c(
			TestingField__c = 'defaultValue'
		);
		TestingObject__c additionalTestingRecord = new TestingObject__c(
			TestingField__c = 'defaultValue'
		);

		insertableRecords.add(testingRecord);
		insertableRecords.add(additionalTestingRecord);

		Database.insert(insertableRecords, true);

		Test.startTest();

		List<TestingObject__c> updatedRecords = TestingObjectController.updateTestingObjects();

		System.assert(updatedRecords.size() == 0, 'Something unexpected happened');

		Test.stopTest();
	}
}